"""
Curated training data for the query complexity classifier.

200+ hand-labeled examples across 4 tiers:
  - simple:    greetings, factual lookups, yes/no, basic math
  - medium:    explanations, summaries, comparisons, simple code
  - complex:   architecture, system design, refactoring, multi-step analysis
  - reasoning: proofs, formal logic, optimization, novel algorithms

You can extend this with your own examples and retrain via the /retrain endpoint.
"""

from typing import List, Tuple

TRAINING_DATA: List[Tuple[str, str]] = [
    # ═══════════════════════════════════════════════════════════════
    # SIMPLE — greetings, yes/no, factual lookups, basic math
    # ═══════════════════════════════════════════════════════════════
    ("Hello", "simple"),
    ("Hi", "simple"),
    ("Hey there", "simple"),
    ("Good morning", "simple"),
    ("Thanks!", "simple"),
    ("Thank you so much", "simple"),
    ("Yes", "simple"),
    ("No", "simple"),
    ("OK", "simple"),
    ("Sure", "simple"),
    ("What is 2 + 2?", "simple"),
    ("What is 10 times 5?", "simple"),
    ("What is the capital of France?", "simple"),
    ("What is the capital of Japan?", "simple"),
    ("Who is the president of the United States?", "simple"),
    ("What color is the sky?", "simple"),
    ("What color is grass?", "simple"),
    ("Is the earth round?", "simple"),
    ("Is water wet?", "simple"),
    ("What day is today?", "simple"),
    ("What time is it?", "simple"),
    ("Translate hello to Spanish", "simple"),
    ("Translate goodbye to French", "simple"),
    ("How do you say thank you in Japanese?", "simple"),
    ("What is the boiling point of water?", "simple"),
    ("How many days in a week?", "simple"),
    ("What is the largest planet?", "simple"),
    ("Who wrote Romeo and Juliet?", "simple"),
    ("What year did World War 2 end?", "simple"),
    ("Is Python a programming language?", "simple"),
    ("What does HTML stand for?", "simple"),
    ("How tall is Mount Everest?", "simple"),
    ("What is the speed of light?", "simple"),
    ("Goodbye", "simple"),
    ("See you later", "simple"),
    ("Help", "simple"),
    ("What is 100 divided by 4?", "simple"),
    ("How many continents are there?", "simple"),
    ("What is the chemical symbol for gold?", "simple"),
    ("Is the sun a star?", "simple"),
    ("The package arrived yesterday.", "simple"),
    ("I like drinking coffee in the morning.", "simple"),
    ("The server is running fine now.", "simple"),
    ("Please close the door.", "simple"),
    ("It is raining outside.", "simple"),
    ("The meeting starts at 10 AM.", "simple"),
    ("The app crashed once today.", "simple"),
    ("I finished the report.", "simple"),
    ("The light is not working.", "simple"),
    ("We shipped the product today.", "simple"),
    ("My account is locked.", "simple"),
    ("I cannot log into the system.", "simple"),
    ("The app keeps crashing on startup.", "simple"),
    ("I was charged twice.", "simple"),
    ("The feature is not working as expected.", "simple"),
    ("My data is missing.", "simple"),
    ("The delivery was delayed.", "simple"),
    ("The UI is confusing.", "simple"),
    ("I am very happy with the service.", "simple"),
    ("This is the worst experience ever.", "simple"),
    ("I feel disappointed.", "simple"),
    ("The support team was amazing.", "simple"),
    ("I am frustrated with the delays.", "simple"),
    ("The product exceeded expectations.", "simple"),
    ("I regret buying this.", "simple"),
    ("I appreciate the quick response.", "simple"),
    ("I feel ignored.", "simple"),
    ("This made my day.", "simple"),
    ("The invoice has been generated.", "simple"),
    ("Payment is pending from the client.", "simple"),
    ("Order ID 4521 has been shipped.", "simple"),
    ("The subscription expires next week.", "simple"),
    ("We received partial payment.", "simple"),
    ("The contract has been signed.", "simple"),
    ("The SSL certificate has expired.", "simple"),
    ("The database connection timed out.", "simple"),
    ("Access token expired.", "simple"),
    ("Traffic peaked at 5 PM.", "simple"),
    ("Active users crossed 10,000.", "simple"),
    ("Server uptime was 99.9%.", "simple"),
    ("Firewall blocked the request.", "simple"),

    # ═══════════════════════════════════════════════════════════════
    # MEDIUM — explanations, summaries, comparisons, simple code
    # ═══════════════════════════════════════════════════════════════
    ("Explain how photosynthesis works", "medium"),
    ("Explain the water cycle", "medium"),
    ("Explain what an API is", "medium"),
    ("Explain the difference between RAM and ROM", "medium"),
    ("What are the differences between HTTP and HTTPS?", "medium"),
    ("Compare Python and JavaScript", "medium"),
    ("Compare React and Angular for frontend development", "medium"),
    ("Compare SQL and NoSQL databases", "medium"),
    ("Summarize the plot of Romeo and Juliet", "medium"),
    ("Summarize the French Revolution", "medium"),
    ("Write a haiku about rain", "medium"),
    ("Write a short poem about the ocean", "medium"),
    ("Write a short paragraph about climate change", "medium"),
    ("Write a brief introduction for a blog post about AI", "medium"),
    ("List 5 benefits of regular exercise", "medium"),
    ("List the top 10 programming languages", "medium"),
    ("Give me 5 tips for better sleep", "medium"),
    ("Write a Python function to reverse a string", "medium"),
    ("Write a JavaScript function to check if a number is prime", "medium"),
    ("Write a simple HTML page with a header and paragraph", "medium"),
    ("Fix this SQL query: SELECT * FORM users WHERE id = 1", "medium"),
    ("Debug this Python code: print('hello'", "medium"),
    ("What is recursion? Give an example", "medium"),
    ("Explain the concept of object-oriented programming", "medium"),
    ("How does a binary search algorithm work?", "medium"),
    ("What is the difference between a stack and a queue?", "medium"),
    ("Explain what Docker is and why it's useful", "medium"),
    ("What are the SOLID principles in software engineering?", "medium"),
    ("Write a regular expression to match email addresses", "medium"),
    ("Explain how DNS works", "medium"),
    ("What is the difference between TCP and UDP?", "medium"),
    ("Write a bash script to count files in a directory", "medium"),
    ("Explain what a REST API is with examples", "medium"),
    ("How do cookies work in web browsers?", "medium"),
    ("What is the difference between authentication and authorization?", "medium"),
    ("Write a CSS flexbox layout for a navigation bar", "medium"),
    ("Explain the MVC design pattern", "medium"),
    ("What are environment variables and how do you use them?", "medium"),
    ("Write a SQL query to find duplicate records", "medium"),
    ("Explain how Git branching works", "medium"),
    ("Please refund the payment of $2500.", "medium"),
    ("Please confirm the transaction status.", "medium"),
    ("The customer requested cancellation.", "medium"),
    ("Generate the tax summary for Q3.", "medium"),
    ("I need help resetting my password.", "medium"),
    ("I want to upgrade my plan.", "medium"),
    ("The Docker container exited unexpectedly.", "medium"),
    ("Kubernetes pod restarted automatically.", "medium"),
    ("Nginx returned a 502 error.", "medium"),
    ("The API returned a 403 response.", "medium"),
    ("Memory leak detected in Node.js app.", "medium"),
    ("Redis cache is not responding.", "medium"),
    ("CPU throttling was observed.", "medium"),
    ("Deployment pipeline failed at build stage.", "medium"),
    ("Fix the null pointer exception in Java.", "medium"),
    ("Add validation to the input field.", "medium"),
    ("Why is my loop running infinitely?", "medium"),
    ("Debug the authentication middleware.", "medium"),
    ("Revenue increased by 12% compared to last quarter.", "medium"),
    ("User retention dropped after redesign.", "medium"),
    ("Conversion rate improved from 3% to 5%.", "medium"),
    ("Bounce rate decreased significantly.", "medium"),
    ("Churn rate remains high.", "medium"),
    ("Cost per acquisition reduced by 15%.", "medium"),
    ("Storage usage reached 90%.", "medium"),
    ("Unauthorized login attempt detected.", "medium"),
    ("Password policy needs updating.", "medium"),
    ("The system may have been compromised.", "medium"),
    ("Enable two-factor authentication.", "medium"),
    ("Audit logs show suspicious activity.", "medium"),
    ("Data encryption is mandatory.", "medium"),
    ("Review GDPR compliance.", "medium"),
    ("Rotate API keys immediately.", "medium"),

    # ═══════════════════════════════════════════════════════════════
    # COMPLEX — architecture, system design, refactoring, multi-step
    # ═══════════════════════════════════════════════════════════════
    ("Design a microservices architecture for an e-commerce platform", "complex"),
    ("Design a scalable chat application architecture", "complex"),
    ("Design a URL shortener service like bit.ly", "complex"),
    ("Design a real-time notification system for a mobile app", "complex"),
    ("Design a content delivery network from scratch", "complex"),
    ("Analyze the pros and cons of PostgreSQL vs MongoDB vs Cassandra for time-series data", "complex"),
    ("Compare different caching strategies for a high-traffic web application", "complex"),
    ("Write a comprehensive REST API specification for a social media platform", "complex"),
    ("Create a detailed technical specification for a payment processing system", "complex"),
    ("Refactor this monolithic application into clean architecture with dependency injection", "complex"),
    ("Refactor a legacy codebase from callbacks to async/await with error handling", "complex"),
    ("Create a deployment strategy for migrating a legacy system to Kubernetes with zero downtime", "complex"),
    ("Design a CI/CD pipeline for a multi-service application with staging environments", "complex"),
    ("Design a data pipeline for processing 10TB of daily log data with real-time analytics", "complex"),
    ("Build an ETL pipeline that ingests data from multiple APIs and loads into a data warehouse", "complex"),
    ("Write a technical specification for end-to-end encryption in a messaging app", "complex"),
    ("Design a comprehensive monitoring and alerting system for distributed microservices", "complex"),
    ("Analyze and optimize performance of a web application handling 100k concurrent users", "complex"),
    ("Create a database schema for a multi-tenant SaaS application with row-level security", "complex"),
    ("Design an authentication system with OAuth2, SAML, and multi-factor authentication", "complex"),
    ("Implement a rate limiting system with sliding window algorithm and distributed state", "complex"),
    ("Design a search engine with full-text search, faceted filtering, and relevance ranking", "complex"),
    ("Create a comprehensive testing strategy for a microservices architecture", "complex"),
    ("Design a disaster recovery plan for a multi-region cloud deployment", "complex"),
    ("Architect a real-time data streaming platform using Kafka and event sourcing", "complex"),
    ("Design a machine learning pipeline for training and deploying models in production", "complex"),
    ("Create a comprehensive API gateway with authentication, rate limiting, and request transformation", "complex"),
    ("Design a distributed task queue system with priority scheduling and dead letter handling", "complex"),
    ("Implement a feature flag system with gradual rollout and A/B testing capabilities", "complex"),
    ("Design a multi-region database replication strategy with conflict resolution", "complex"),
    ("If the payment fails three times, disable the account and notify admin.", "complex"),
    ("Classify this email as spam or not spam and explain your reasoning.", "complex"),
    ("Summarize this paragraph about AI trends.", "complex"),
    ("Detect intent from the user message and route accordingly.", "complex"),
    ("Extract the order number from this text and validate it.", "complex"),
    ("Identify sentiment and suggest a response template.", "complex"),
    ("Suggest optimization if CPU stays above 85%.", "complex"),
    ("Determine if this code has a bug and explain the fix.", "complex"),

    # ═══════════════════════════════════════════════════════════════
    # REASONING — proofs, formal logic, optimization, novel algorithms
    # ═══════════════════════════════════════════════════════════════
    ("Prove that the square root of 2 is irrational", "reasoning"),
    ("Prove that there are infinitely many prime numbers", "reasoning"),
    ("Prove the fundamental theorem of calculus", "reasoning"),
    ("Prove that the halting problem is undecidable", "reasoning"),
    ("Prove that P is a subset of NP and discuss implications", "reasoning"),
    ("Derive the time complexity of the Ackermann function", "reasoning"),
    ("Derive the closed-form solution for the Fibonacci sequence using matrix exponentiation", "reasoning"),
    ("Design an algorithm to solve the traveling salesman problem with time windows and capacity constraints", "reasoning"),
    ("Design a novel lock-free concurrent data structure for a priority queue with linearizability", "reasoning"),
    ("Design a consensus algorithm for Byzantine fault-tolerant distributed systems", "reasoning"),
    ("Formally verify the correctness of a concurrent garbage collector using temporal logic", "reasoning"),
    ("Solve this optimization: minimize supply chain cost with 20 warehouses, 50 stores, stochastic demand", "reasoning"),
    ("Debug this race condition in a distributed lock implementation using Redis with multiple replicas", "reasoning"),
    ("Analyze the computational complexity of this recursive algorithm and prove its correctness", "reasoning"),
    ("Derive the optimal strategy for a multi-armed bandit problem with non-stationary rewards", "reasoning"),
    ("Prove the correctness of Dijkstra's algorithm using loop invariants", "reasoning"),
    ("Design a zero-knowledge proof system for verifying computation without revealing inputs", "reasoning"),
    ("Prove that regular languages are closed under complementation using the Myhill-Nerode theorem", "reasoning"),
    ("Derive the information-theoretic lower bound for comparison-based sorting", "reasoning"),
    ("Analyze the amortized complexity of a Fibonacci heap and prove the decrease-key bound", "reasoning"),
    ("Prove the CAP theorem and discuss its practical implications for distributed databases", "reasoning"),
    ("Design an optimal algorithm for the online bin packing problem with competitive ratio analysis", "reasoning"),
    ("Formally prove the correctness of the Raft consensus algorithm under network partitions", "reasoning"),
    ("Derive the VC dimension of neural networks with ReLU activations", "reasoning"),
    ("Prove that context-free languages are not closed under intersection using a counterexample", "reasoning"),
    ("Design a differentially private mechanism for aggregate queries with optimal noise bounds", "reasoning"),
    ("Prove the minimax theorem for zero-sum games and derive Nash equilibrium conditions", "reasoning"),
    ("Analyze the convergence properties of gradient descent for non-convex optimization", "reasoning"),
    ("Prove the impossibility of distributed consensus in asynchronous systems with one faulty process", "reasoning"),
    ("Derive the optimal regret bound for the UCB algorithm in stochastic bandits", "reasoning"),
    ("If sales increase by 20% and costs remain the same, profit will rise.", "reasoning"),
    ("The system slowed down after the update, so the patch might be faulty.", "reasoning"),
    ("If the user enters invalid data, the form should reject submission.", "reasoning"),
    ("Since demand dropped, production was reduced.", "reasoning"),
    ("If memory usage exceeds 80%, restart the service.", "reasoning"),
    ("Because traffic doubled, we scaled the instance.", "reasoning"),
    ("If the user is premium, unlock advanced features.", "reasoning"),
    ("When CPU usage spikes, logs must be checked.", "reasoning"),
    ("If latency increases, investigate network routing.", "reasoning"),
    ("Since the file is missing, the script failed.", "reasoning"),
]
